2023-12-05 11:37:14,764 : INFO : root : Loading config.
2023-12-05 11:37:14,871 : INFO : ConfigProcessor : Config spec file cache created: /tmp/config_spec.mpf_cache
2023-12-05 11:37:14,871 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2023-12-05 11:37:14,872 : INFO : ConfigProcessor : Loading config from file /home/ohm/.local/lib/python3.10/site-packages/mpf/mpfconfig.yaml.
2023-12-05 11:37:14,916 : INFO : ConfigProcessor : Loading config: /home/ohm/.local/lib/python3.10/site-packages/mpf/mpfconfig.yaml
2023-12-05 11:37:14,917 : INFO : ConfigProcessor : Loading config from file /home/ohm/dodgeball/config/config.yaml.
2023-12-05 11:37:14,926 : INFO : ConfigProcessor : Loading config: /home/ohm/dodgeball/config/config.yaml
2023-12-05 11:37:14,927 : INFO : ConfigProcessor : Loading config: /home/ohm/dodgeball/config/lights.yaml
2023-12-05 11:37:14,930 : INFO : ConfigProcessor : Loading config: /home/ohm/dodgeball/config/coils.yaml
2023-12-05 11:37:14,933 : INFO : ConfigProcessor : Loading config: /home/ohm/dodgeball/config/switches.yaml
2023-12-05 11:37:14,935 : INFO : ConfigProcessor : Loading config: /home/ohm/dodgeball/config/playervars.yaml
2023-12-05 11:37:14,938 : INFO : ConfigProcessor : Config file cache created: /tmp/bf38e15644d30ba1eb87297a18d33bd2.mpf_cache
2023-12-05 11:37:15,038 : INFO : ConfigProcessor : Loading config from file /home/ohm/.local/lib/python3.10/site-packages/mpf/modes/attract/config/attract.yaml.
2023-12-05 11:37:15,040 : INFO : ConfigProcessor : Loading config: /home/ohm/.local/lib/python3.10/site-packages/mpf/modes/attract/config/attract.yaml
2023-12-05 11:37:15,040 : INFO : ConfigProcessor : Loading config from file /home/ohm/dodgeball/modes/attract/config/attract.yaml.
2023-12-05 11:37:15,041 : INFO : ConfigProcessor : Loading config: /home/ohm/dodgeball/modes/attract/config/attract.yaml
2023-12-05 11:37:15,041 : INFO : ConfigProcessor : Config file cache created: /tmp/ecc2466debc0cbb894d1a2fba8912b38.mpf_cache
2023-12-05 11:37:15,042 : INFO : ConfigProcessor : Loading config from file /home/ohm/.local/lib/python3.10/site-packages/mpf/modes/game/config/game.yaml.
2023-12-05 11:37:15,043 : INFO : ConfigProcessor : Loading config: /home/ohm/.local/lib/python3.10/site-packages/mpf/modes/game/config/game.yaml
2023-12-05 11:37:15,044 : INFO : ConfigProcessor : Config file cache created: /tmp/32cc0edc83e6cd7fce5d5a48c9d631d2.mpf_cache
2023-12-05 11:37:15,044 : INFO : ConfigProcessor : Loading config from file /home/ohm/dodgeball/modes/base/config/base.yaml.
2023-12-05 11:37:15,047 : INFO : ConfigProcessor : Loading config: /home/ohm/dodgeball/modes/base/config/base.yaml
2023-12-05 11:37:15,048 : INFO : ConfigProcessor : Loading config: /home/ohm/dodgeball/modes/base/config/shots.yaml
2023-12-05 11:37:15,049 : INFO : ConfigProcessor : Config file cache created: /tmp/0fe63fd00a83faf3a344d3dd33ac8b6e.mpf_cache
2023-12-05 11:37:15,050 : INFO : ConfigProcessor : Loading config from file /home/ohm/dodgeball/modes/attract/shows/./attract_display_loop.yaml.
2023-12-05 11:37:15,052 : INFO : ConfigProcessor : Loading config: /home/ohm/dodgeball/modes/attract/shows/./attract_display_loop.yaml
2023-12-05 11:37:15,053 : INFO : ConfigProcessor : Config file cache created: /tmp/4923a60b897e22ae41d9973250e86152.mpf_cache
2023-12-05 11:37:15,053 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0.dev32
2023-12-05 11:37:15,054 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2023-12-05-11-37-14-mpf-dodgeball.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2023-12-05 11:37:15,054 : INFO : Machine : MPF path: /home/ohm/.local/lib/python3.10/site-packages/mpf
2023-12-05 11:37:15,054 : INFO : Machine : Machine path: /home/ohm/dodgeball
2023-12-05 11:37:15,054 : INFO : Machine : Platform: linux
2023-12-05 11:37:15,054 : INFO : Machine : Python executable location: /usr/bin/python3
2023-12-05 11:37:15,054 : INFO : Machine : Python version: 3.10.12 (64-bit)
2023-12-05 11:37:15,071 : INFO : Machine : Initializing MPF...
2023-12-05 11:37:15,186 : INFO : P-Roc : Connecting to P-ROC
2023-12-05 11:37:15,454 : INFO : P-Roc : Successfully connected to P-ROC/P3-ROC. Firmware Version: 2. Firmware Revision: 18. Hardware Board ID: 3
2023-12-05 11:37:15,466 : INFO : EventManager : Event: ======'machine_var_p_roc_version'====== Args={'value': 2, 'prev_value': None, 'change': True}
2023-12-05 11:37:15,466 : INFO : EventManager : Event: ======'machine_var_p_roc_revision'====== Args={'value': 18, 'prev_value': None, 'change': True}
2023-12-05 11:37:15,466 : INFO : EventManager : Event: ======'machine_var_p_roc_hardware_version'====== Args={'value': 3, 'prev_value': None, 'change': True}
2023-12-05 11:37:15,467 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2023-12-05 11:37:15,558 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2023-12-05 11:37:15,558 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev32', 'prev_value': None, 'change': True}
2023-12-05 11:37:15,558 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev32, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2023-12-05 11:37:15,558 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.10.12', 'prev_value': None, 'change': True}
2023-12-05 11:37:15,562 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Linux-6.2.0-37-generic-x86_64-with-glibc2.35', 'prev_value': None, 'change': True}
2023-12-05 11:37:15,562 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Linux', 'prev_value': None, 'change': True}
2023-12-05 11:37:15,562 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '6.2.0-37-generic', 'prev_value': None, 'change': True}
2023-12-05 11:37:15,562 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '#38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2', 'prev_value': None, 'change': True}
2023-12-05 11:37:15,562 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2023-12-05 11:37:15,562 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2023-12-05 11:37:15,595 : INFO : EventManager : Event: ======'logicblock_has_highscore_updated'====== Args={'value': 0, 'enabled': True}
2023-12-05 11:37:15,596 : INFO : EventManager : Event: ======'logicblock_has_highscore_updated'====== Args={'value': 0, 'enabled': True}
2023-12-05 11:37:15,598 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2023-12-05 11:37:15,614 : INFO : SwitchController : Found active switch: (3, <Platform.P3-ROC>) <switch.s_trougheject_p1>
2023-12-05 11:37:15,614 : INFO : SwitchController : Found active switch: (11, <Platform.P3-ROC>) <switch.s_trougheject_p2>
2023-12-05 11:37:15,618 : ERROR : asyncio : Exception in callback <bound method EventManager._queue_task_done of <mpf.core.events.EventManager object at 0x7f13d69609a0>>
handle: <Handle EventManager._queue_task_done>
Traceback (most recent call last):
  File "/home/ohm/.local/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
OSError: [Errno 16] Device or resource busy: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/events.py", line 791, in _queue_task_done
    future.result()
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/mode_controller.py", line 107, in initialize_modes
    mode.initialize_mode()
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/mode.py", line 550, in initialize_mode
    self.mode_init()
  File "/home/ohm/dodgeball/modes/base/code/base.py", line 11, in mode_init
    ser = serial.Serial("/dev/ttyACM0", 115200)
  File "/home/ohm/.local/lib/python3.10/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/ohm/.local/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 16] could not open port /dev/ttyACM0: [Errno 16] Device or resource busy: '/dev/ttyACM0'
2023-12-05 11:37:15,624 : INFO : Machine : Starting the main run loop.
2023-12-05 11:37:15,625 : INFO : Machine : Shutting down...
2023-12-05 11:37:15,625 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2023-12-05 11:37:16,627 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/home/ohm/.local/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
OSError: [Errno 16] Device or resource busy: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/events.py", line 791, in _queue_task_done
    future.result()
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/mode_controller.py", line 107, in initialize_modes
    mode.initialize_mode()
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/mode.py", line 550, in initialize_mode
    self.mode_init()
  File "/home/ohm/dodgeball/modes/base/code/base.py", line 11, in mode_init
    ser = serial.Serial("/dev/ttyACM0", 115200)
  File "/home/ohm/.local/lib/python3.10/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/ohm/.local/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 16] could not open port /dev/ttyACM0: [Errno 16] Device or resource busy: '/dev/ttyACM0'
2023-12-05 11:37:31,952 : ERROR : root : Received second SIGINT. Will exit ungracefully!
Traceback (most recent call last):
  File "/home/ohm/.local/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
OSError: [Errno 16] Device or resource busy: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/events.py", line 791, in _queue_task_done
    future.result()
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/mode_controller.py", line 107, in initialize_modes
    mode.initialize_mode()
  File "/home/ohm/.local/lib/python3.10/site-packages/mpf/core/mode.py", line 550, in initialize_mode
    self.mode_init()
  File "/home/ohm/dodgeball/modes/base/code/base.py", line 11, in mode_init
    ser = serial.Serial("/dev/ttyACM0", 115200)
  File "/home/ohm/.local/lib/python3.10/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/ohm/.local/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 16] could not open port /dev/ttyACM0: [Errno 16] Device or resource busy: '/dev/ttyACM0'
